#!/bin/bash
set -ue
container_name=www.dontferget.club
image_name=dontferget-wisp
echo deploying
eval $(docker-machine env www.dontferget.club)
docker build -t $image_name .
docker rm -f $container_name || :
docker run -d \
  --restart always \
  -p 80:80 \
  --name $container_name \
  -e MONGO_HOST=10.99.0.10 \
  -e MONGO_DATABASE=todo \
  -e WUNDERLIST_CLIENT_ID=468e63e2114a73908b17 \
  -e WUNDERLIST_CLIENT_SECRET=$(./scripts/secret wunderlist/secret) \
  -e SESSION_SECRET=foobar \
  $image_name
echo done
