#!/bin/bash
set -ue
function global_install {
  if [ -f /etc/arch-release ]; then
    cmd='pacman -S'
  elif which apt-get 2>/dev/null >/dev/null; then
    cmd='apt-get install'
  else
    cmd='echo SKIPPING: No known package manager && :'
  fi
  echo Installing $1
  eval "sudo $cmd $1"
}
global_install docker
global_install docker-machine
docker pull node
cd src
npm install -D
