#!/bin/bash
set -ue
eval $(docker-machine env -u)
docker rm -f devmongo || :
docker run -d --name devmongo mongo
docker run -it \
  --link devmongo:mongohost \
  -e MONGO_HOST=mongohost \
  -e MONGO_DATABASE=todo \
  -w /app \
  -v $PWD/src:/app \
  -p 80:80 \
  node bash
